// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_500 from "./routes/_500.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $register from "./routes/register.tsx";
import * as $test from "./routes/test.tsx";
import * as $ui from "./routes/ui.tsx";
import * as $AuthStateManager_index from "./islands/AuthStateManager/index.tsx";
import * as $Components_Header_index from "./islands/Components/Header/index.tsx";
import * as $Components_Header_varient_v1 from "./islands/Components/Header/varient/v1.tsx";
import * as $Components_Header_varient_v2 from "./islands/Components/Header/varient/v2.tsx";
import * as $Components_Header_varient_v3 from "./islands/Components/Header/varient/v3.tsx";
import * as $Components_LoginForm_index from "./islands/Components/LoginForm/index.tsx";
import * as $Components_RegisterForm_index from "./islands/Components/RegisterForm/index.tsx";
import * as $Components_SignForm_index from "./islands/Components/SignForm/index.tsx";
import * as $ContextHooks_useSnackBarPopUp from "./islands/ContextHooks/useSnackBarPopUp.tsx";
import * as $ContextHooks_useThemeContext from "./islands/ContextHooks/useThemeContext.tsx";
import * as $ContextHooks_useUserContext from "./islands/ContextHooks/useUserContext.tsx";
import * as $SnackBarManager_index from "./islands/SnackBarManager/index.tsx";
import * as $TestIsland_SnackBar from "./islands/TestIsland/SnackBar.tsx";
import * as $ThemeManager_index from "./islands/ThemeManager/index.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_500.tsx": $_500,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/joke.ts": $api_joke,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/register.tsx": $register,
    "./routes/test.tsx": $test,
    "./routes/ui.tsx": $ui,
  },
  islands: {
    "./islands/AuthStateManager/index.tsx": $AuthStateManager_index,
    "./islands/Components/Header/index.tsx": $Components_Header_index,
    "./islands/Components/Header/varient/v1.tsx": $Components_Header_varient_v1,
    "./islands/Components/Header/varient/v2.tsx": $Components_Header_varient_v2,
    "./islands/Components/Header/varient/v3.tsx": $Components_Header_varient_v3,
    "./islands/Components/LoginForm/index.tsx": $Components_LoginForm_index,
    "./islands/Components/RegisterForm/index.tsx":
      $Components_RegisterForm_index,
    "./islands/Components/SignForm/index.tsx": $Components_SignForm_index,
    "./islands/ContextHooks/useSnackBarPopUp.tsx":
      $ContextHooks_useSnackBarPopUp,
    "./islands/ContextHooks/useThemeContext.tsx": $ContextHooks_useThemeContext,
    "./islands/ContextHooks/useUserContext.tsx": $ContextHooks_useUserContext,
    "./islands/SnackBarManager/index.tsx": $SnackBarManager_index,
    "./islands/TestIsland/SnackBar.tsx": $TestIsland_SnackBar,
    "./islands/ThemeManager/index.tsx": $ThemeManager_index,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
